import type { Digsite } from "./materials";

export const digsiteArtifacts = {
  "Kharid-et": [
    "'Animate Dead'",
    "'Consensus ad Idem'",
    "'Exsanguinate'",
    "'Incite Fear'",
    "'Prima Legio'",
    "'Smoke Cloud'",
    "'Solem in Umbra'",
    "Ancient",
    "Battle plans",
    "Ceremonial mace",
    "Legatus",
    "Legionary",
    "Necromantic focus",
    "Pontifex",
    "Portable phylactery",
    "Praetorian",
    "Primis Elementis",
    "Venator",
    "Vigorem vial",
    "Zaros effigy",
    "Zarosian",
  ],
  "Infernal Source": [
    "'Disorder' painting",
    "'Lust' metal sculpture",
    "'Pandemonium' tapestry",
    "'Possession' metal sculpture",
    "'The Lake of Fire' painting",
    "'Torment' metal sculpture",
    "Branding iron",
    "Chaos",
    "Crest of Dagon",
    "Greater demon",
    "Hellfire",
    "Hookah pipe",
    "Imp mask",
    "Larupia trophy",
    "Lesser demon",
    "Lion trophy",
    "Manacles",
    "Opulent wine goblet",
    "Order of Dis",
    "Ritual dagger",
    "She-wolf trophy",
    "Spiked dog collar",
    "Trishula",
    "Tsutsaroth",
    "Virius trophy",
  ],
  Everlight: [
    "'Frying pan'",
    "'Hallowed Be the Everlight' painting",
    "'The Enlightened Soul' scroll",
    "'The Eudoxian Elements' tablet",
    "'The Lord of Light' painting",
    "'The Pride of Padosan' painting",
    "Amphora",
    "Bronze Dominion medal",
    "Ceremonial unicorn",
    "Decorative vase",
    "Dominarian device",
    "Dominion",
    "Doru spear",
    "Everlight",
    "Fishing trident",
    "Folded-arm figurine",
    "Hallowed lantern",
    "Kantharos cup",
    "Kontos lance",
    "Kopis dagger",
    "Patera bowl",
    "Rod of Asclepius",
    "Silver Dominion medal",
    "Xiphos short sword",
  ],
  Senntisten: [
    "'The Serpent's Fall' carving",
    "Apex cap",
    "Curse tablet",
    "Decorative amphora",
    "Funerary urn",
    "Gladiator",
    "Hand of the Ancients",
    "Infula robes",
    "Inquisitor's",
    "Loarnab rod",
    "Model chariot",
  ],
  Stormguard: [
    "Avian song-egg player",
    "Aviansie dreamcoat",
    "Blackfire lance",
    "Ceremonial plume",
    "Chuluu stone",
    "Dayguard shield",
    "Flat cap",
    "Golem",
    "Hawkeye lens multi-vision scope",
    "Ikovian gerege",
    "Keshik",
    "Morin khuur",
    "Night owl flight goggles",
    "Nightguard shield",
    "Peacocking parasol",
    "Prototype",
    "Quintessence counter",
    "Songbird recorder",
    "Spherical astrolabe",
    "Stormguard gerege",
    "Talon-3 razor wing",
    "Toy",
  ],
  Daemonheim: [
    "'Friendship bracelet'",
    "Castle gatestone",
    "Comfort gatestone",
    "Engraved ring of kinship",
    "Excavator portal mine",
    "Exploratory totem",
    "Golden projection 'needle'",
    "Halak's cube",
    "Homely totem",
    "Plant seed satchel",
    "Portable portal generator",
    "Projection attuner",
    "Snuff box",
    "Spent summoning charm",
    "Storage totem",
    "Warped trinket",
  ],
  Warforge: [
    "'Da Boss Man' sculpture",
    "'Forged in War' sculpture",
    "'Nosorog!' sculpture",
    "Beastkeeper helm",
    "Dorgeshuun spear",
    "Drogokishuun hook sword",
    "Ekeleshuun blinder mask",
    "Garagorshuun anchor",
    "High priest",
    "Hobgoblin mansticker",
    "Horogothgar cooking pot",
    "Huzamogaarb chaos crown",
    "Idithuun horn ring",
    "Kal-i-kra",
    "Narogoshuun 'Hob-da-Gob' ball",
    "Ogre Kyzaj axe",
    "Ork cleaver sword",
    "Ourg",
    "Rekeshuun war tether",
    "Saragorgak star crown",
    "Thorobshuun battle standard",
    "Yurkolgokh stink grenade",
  ],
  Orthen: [
    "'Raksha' idol",
    "Death mask",
    "Dragon burner",
    "Dragon scalpel",
    "Dragonkin",
    "Gold dish",
    "Kilaya",
    "Lingam stone",
    "Master control",
    "Meditation pipe",
    "Orthenglass flask",
    "Pasaha",
    "Personal totem",
    "Protective goggles",
    "Ritual bell",
    "Singing bowl",
    "Vazara",
    "Xolo",
  ],
  Moonrise: [
    "Lunar calendar",
    "Wolf statuette",
    "Ivory sickle",
    "Nakkirian seal",
    "Royal Game of Ba",
    "Backstrap loom",
    "Animal doll",
    "Initiate's kaunake",
    "Offering bowl",
    "Incense burner",
    "Bloodwine",
    "Reagent jar",
    "Ninbaradari mural",
    "Bloodletting dagger",
    "Fang of Kayazu",
  ],
} as const satisfies Record<Digsite, readonly string[]>;
