export const digsiteMaterials = {
  "Kharid-et": [
    "Ancient vis",
    "Blood of Orcus",
    "Goldrune",
    "Imperial steel",
    "Samite silk",
    "Third Age iron",
    "Tyrian purple",
    "Vellum",
    "White oak",
    "Zarosian insignia",
  ],
  "Infernal Source": [
    "Animal furs",
    "Cadmium red",
    "Chaotic brimstone",
    "Demonhide",
    "Eye of Dagon",
    "Goldrune",
    "Hellfire metal",
    "Leather scraps",
    "Orthenglass",
    "Samite silk",
    "Third Age iron",
    "Vellum",
    "White oak",
  ],
  Everlight: [
    "Cobalt blue",
    "Everlight silvthril",
    "Goldrune",
    "Keramos",
    "Leather scraps",
    "Orthenglass",
    "Samite silk",
    "Star of Saradomin",
    "Third Age iron",
    "Vellum",
    "White marble",
    "White oak",
  ],
  Senntisten: [
    "Ancient vis",
    "Blood of Orcus",
    "Goldrune",
    "Imperial steel",
    "Leather scraps",
    "Samite silk",
    "Soapstone",
    "Tyrian purple",
    "Vellum",
    "White oak",
    "Zarosian insignia",
  ],
  Stormguard: [
    "Aetherium alloy",
    "Animal furs",
    "Armadylean yellow",
    "Goldrune",
    "Leather scraps",
    "Orthenglass",
    "Quintessence",
    "Samite silk",
    "Soapstone",
    "Stormguard steel",
    "Third Age iron",
    "Vellum",
    "White oak",
    "Wings of War",
  ],
  Daemonheim: [
    "Carbon black",
    "Chaotic brimstone",
    "Compass rose",
    "Dragon metal",
    "Eye of Dagon",
    "Felt",
    "Goldrune",
    "Orgone",
    "Orthenglass",
    "Soapstone",
  ],
  Warforge: [
    "Animal furs",
    "Fossilised bone",
    "Goldrune",
    "Leather scraps",
    "Malachite green",
    "Mark of the Kyzaj",
    "Samite silk",
    "Soapstone",
    "Third Age iron",
    "Vulcanised rubber",
    "Warforged bronze",
    "White oak",
    "Yu'biusk clay",
  ],
  Orthen: [
    "Carbon black",
    "Compass rose",
    "Dragon metal",
    "Felt",
    "Goldrune",
    "Orgone",
    "Orthenglass",
    "Soapstone",
  ],
  Moonrise: [
    "Banded limestone",
    "Burnt umber",
    "Cashmere",
    "Ivory",
    "Triskelion",
    "White oak",
  ],
} as const;

export type ArchaeologyDigsite = keyof typeof digsiteMaterials;
